server:
  port: 18080
#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chinacity?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  thymeleaf: #thymeleaf组件
    cache: false
    prefix: classpath:/template/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

  redis:
    host: 127.0.0.1
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 300ms # 连接超时时间（毫秒）

#mybatis别名
mybatis:
  type-aliases-package: com.spiderpoi.spider.dao
  mapper-locations: classpath:dao/*.xml #加载映射文件
#日志
logging:
  level:
    root: info